version: "3.8"

volumes:
  db-data:

services:
  db:
    image: mariadb:10.7.4
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env
    network_mode: service:db
    command: sleep infinity
    volumes:
      - ..:/workspace:cached